config/routes.rb
IclassApi::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :options
    resources :surveys
    resources :user_device_tokens
    resources :votes
    resources :attendances
    resources :questions
    resources :talks
    resources :users
  end

  namespace :api do
    devise_for :users
    match '/sign_up' => 'registrations#create', :via => :post, :as => 'sign_up'
    match '/sign_in' => 'sessions#create', :via => :post, :as => 'sign_in'
    match '/sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'
    resources :talks, :only => [:create,:index]
    resources :talks do
      member do
        post 'join'
        post 'start'
        post 'close'
        post 'leave'
      end
      resources :questions, :only => [:create, :index]
      resources :questions do
        member do
          post 'vote'
        end
      end
      resources :surveys
    end
    match '/joined_talks' => 'talks#joined_talks', :via => :get, :as => 'joined_talks'
    match '/talks/passcode/:passcode' => 'talks#get_by_passcode', :via => :get, :as => 'get_by_passcode'
    match '/update_device_token' => 'users#update_device_token', :via => :post, :as => 'update_device_token'
  end

end

app/models/user_device_token.rb
class UserDeviceToken < ActiveRecord::Base
  belongs_to :user
  attr_accessible :device_token, :user, :user_id
end

app/controllers/admin/user_device_tokens_controller.rb
class Admin::UserDeviceTokensController < Admin::ApplicationController
  # GET /user_device_tokens
  # GET /user_device_tokens.json
  def index
    @user_device_tokens = UserDeviceToken.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_device_tokens }
    end
  end

  # GET /user_device_tokens/1
  # GET /user_device_tokens/1.json
  def show
    @user_device_token = UserDeviceToken.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_device_token }
    end
  end

  # GET /user_device_tokens/new
  # GET /user_device_tokens/new.json
  def new
    @user_device_token = UserDeviceToken.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_device_token }
    end
  end

  # GET /user_device_tokens/1/edit
  def edit
    @user_device_token = UserDeviceToken.find(params[:id])
  end

  # POST /user_device_tokens
  # POST /user_device_tokens.json
  def create
    @user_device_token = UserDeviceToken.new(params[:user_device_token])

    respond_to do |format|
      if @user_device_token.save
        format.html { redirect_to @user_device_token, notice: 'User device token was successfully created.' }
        format.json { render json: @user_device_token, status: :created, location: @user_device_token }
      else
        format.html { render action: "new" }
        format.json { render json: @user_device_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_device_tokens/1
  # PUT /user_device_tokens/1.json
  def update
    @user_device_token = UserDeviceToken.find(params[:id])

    respond_to do |format|
      if @user_device_token.update_attributes(params[:user_device_token])
        format.html { redirect_to @user_device_token, notice: 'User device token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_device_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_device_tokens/1
  # DELETE /user_device_tokens/1.json
  def destroy
    @user_device_token = UserDeviceToken.find(params[:id])
    @user_device_token.destroy

    respond_to do |format|
      format.html { redirect_to user_device_tokens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_device_tokens_helper.rb
module UserDeviceTokensHelper
end

app/views/admin/user_device_tokens/_form.html.erb
<%= form_for(@user_device_token) do |f| %>
  <% if @user_device_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_device_token.errors.count, "error") %> prohibited this user_device_token from being saved:</h2>

      <ul>
      <% @user_device_token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :device_token %><br />
    <%= f.text_field :device_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/user_device_tokens/edit.html.erb
<h1>Editing user_device_token</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_device_token_path(@user_device_token) %> |
<%= link_to 'Back', admin_user_device_tokens_path %>

app/views/admin/user_device_tokens/index.html.erb
<h1>Listing user_device_tokens</h1>

<table>
  <tr>
    <th>User</th>
    <th>Device token</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_device_tokens.each do |user_device_token| %>
  <tr>
    <td><%= user_device_token.user %></td>
    <td><%= user_device_token.device_token %></td>
    <td><%= link_to 'Show', admin_user_device_token_path(user_device_token) %></td>
    <td><%= link_to 'Edit', edit_admin_user_device_token_path(user_device_token) %></td>
    <td><%= link_to 'Destroy', admin_user_device_token_path(user_device_token), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User device token', new_admin_user_device_token_path %>

app/views/admin/user_device_tokens/new.html.erb
<h1>New user_device_token</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_user_device_tokens_path %>

app/views/admin/user_device_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_device_token.user %>
</p>

<p>
  <b>Device token:</b>
  <%= @user_device_token.device_token %>
</p>


<%= link_to 'Edit', edit_admin_user_device_token_path(@user_device_token) %> |
<%= link_to 'Back', admin_user_device_tokens_path %>