config/routes.rb
IclassApi::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :options
    resources :surveys
    resources :user_device_tokens
    resources :votes
    resources :attendances
    resources :questions
    resources :talks
    resources :users
  end

  namespace :api do
    devise_for :users
    match '/sign_up' => 'registrations#create', :via => :post, :as => 'sign_up'
    match '/sign_in' => 'sessions#create', :via => :post, :as => 'sign_in'
    match '/sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'
    resources :talks, :only => [:create,:index]
    resources :talks do
      member do
        post 'join'
        post 'start'
        post 'close'
        post 'leave'
      end
      resources :questions, :only => [:create, :index]
      resources :questions do
        member do
          post 'vote'
        end
      end
      resources :surveys
    end
    match '/joined_talks' => 'talks#joined_talks', :via => :get, :as => 'joined_talks'
    match '/talks/passcode/:passcode' => 'talks#get_by_passcode', :via => :get, :as => 'get_by_passcode'
    match '/update_device_token' => 'users#update_device_token', :via => :post, :as => 'update_device_token'
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  MULTIPLE_CHOICES = 1
  FREE_TEXT = 2
  attr_accessible :question, :talk, :survey_type, :talk_id, :options_attributes
  belongs_to :talk
  has_many :options

  before_save :must_have_at_least_two_options

  accepts_nested_attributes_for :options

  def must_have_at_least_two_options
    return false if options.size < 2 and survey_type == MULTIPLE_CHOICES
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/api/surveys_controller.rb
class Api::SurveysController < Api::BaseController
  ensure_param_exists :auth_token, :talk_id
  before_filter :ensure_talk_id_exists
  before_filter :ensure_auth_token_exists, :only =>[:create]
  def create
    begin
      talk = Talk.find params[:talk_id]
      survey = Survey.new(params[:survey])
      survey.talk_id = talk.id
      if survey.save
        render :json => {:success => TRUE_VALUE, :survey => survey}, :status => 200
      else
        render :json => {:success => FALSE_VALUE, :message => "unable to create survey"}, :status => 422
      end
    rescue ActiveRecord::RecordNotFound
      render :json => {:success => FALSE_VALUE, :message => "unable to find talk with id #{params[:talk_id]}"}, :status => 422
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/admin/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :talk %><br />
    <%= f.text_field :talk %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_survey_path(@survey) %> |
<%= link_to 'Back', admin_surveys_path %>

app/views/admin/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Question</th>
    <th>Talk</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.type %></td>
    <td><%= survey.question %></td>
    <td><%= survey.talk %></td>
    <td><%= link_to 'Show', admin_survey_path(survey) %></td>
    <td><%= link_to 'Edit', edit_admin_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', admin_survey_path(survey), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_admin_survey_path %>

app/views/admin/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_surveys_path %>

app/views/admin/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @survey.type %>
</p>

<p>
  <b>Question:</b>
  <%= @survey.question %>
</p>

<p>
  <b>Talk:</b>
  <%= @survey.talk %>
</p>


<%= link_to 'Edit', edit_admin_survey_path(@survey) %> |
<%= link_to 'Back', admin_surveys_path %>