config/routes.rb
IclassApi::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :options
    resources :surveys
    resources :user_device_tokens
    resources :votes
    resources :attendances
    resources :questions
    resources :talks
    resources :users
  end

  namespace :api do
    devise_for :users
    match '/sign_up' => 'registrations#create', :via => :post, :as => 'sign_up'
    match '/sign_in' => 'sessions#create', :via => :post, :as => 'sign_in'
    match '/sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'
    resources :talks, :only => [:create,:index]
    resources :talks do
      member do
        post 'join'
        post 'start'
        post 'close'
        post 'leave'
      end
      resources :questions, :only => [:create, :index]
      resources :questions do
        member do
          post 'vote'
        end
      end
      resources :surveys
    end
    match '/joined_talks' => 'talks#joined_talks', :via => :get, :as => 'joined_talks'
    match '/talks/passcode/:passcode' => 'talks#get_by_passcode', :via => :get, :as => 'get_by_passcode'
    match '/update_device_token' => 'users#update_device_token', :via => :post, :as => 'update_device_token'
  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :talk

  attr_accessible :end_time, :start_time, :talk_id, :user_id
  def as_json(options={})
    super()
  end
end

app/controllers/admin/attendances_controller.rb
class Admin::AttendancesController < Admin::ApplicationController
  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendances }
    end
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendance }
    end
  end

  # GET /attendances/new
  # GET /attendances/new.json
  def new
    @attendance = Attendance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendance }
    end
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(params[:attendance])

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render json: @attendance, status: :created, location: @attendance }
      else
        format.html { render action: "new" }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendances/1
  # PUT /attendances/1.json
  def update
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      if @attendance.update_attributes(params[:attendance])
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/admin/attendances/_form.html.erb
<%= form_for(@attendance) do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :talk %><br />
    <%= f.text_field :talk %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_attendance_path(@attendance) %> |
<%= link_to 'Back', admin_attendances_path %>

app/views/admin/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <tr>
    <th>User</th>
    <th>Talk</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.user %></td>
    <td><%= attendance.talk %></td>
    <td><%= attendance.start_time %></td>
    <td><%= attendance.end_time %></td>
    <td><%= link_to 'Show', admin_attendance_path(attendance) %></td>
    <td><%= link_to 'Edit', edit_admin_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', admin_attendance_path(attendance), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance', new_admin_attendance_path %>

app/views/admin/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_attendances_path %>

app/views/admin/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attendance.user %>
</p>

<p>
  <b>Talk:</b>
  <%= @attendance.talk %>
</p>

<p>
  <b>Start time:</b>
  <%= @attendance.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @attendance.end_time %>
</p>


<%= link_to 'Edit', edit_admin_attendance_path(@attendance) %> |
<%= link_to 'Back', admin_attendances_path %>