config/routes.rb
IclassApi::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :options
    resources :surveys
    resources :user_device_tokens
    resources :votes
    resources :attendances
    resources :questions
    resources :talks
    resources :users
  end

  namespace :api do
    devise_for :users
    match '/sign_up' => 'registrations#create', :via => :post, :as => 'sign_up'
    match '/sign_in' => 'sessions#create', :via => :post, :as => 'sign_in'
    match '/sign_out' => 'sessions#destroy', :via => :delete, :as => 'sign_out'
    resources :talks, :only => [:create,:index]
    resources :talks do
      member do
        post 'join'
        post 'start'
        post 'close'
        post 'leave'
      end
      resources :questions, :only => [:create, :index]
      resources :questions do
        member do
          post 'vote'
        end
      end
      resources :surveys
    end
    match '/joined_talks' => 'talks#joined_talks', :via => :get, :as => 'joined_talks'
    match '/talks/passcode/:passcode' => 'talks#get_by_passcode', :via => :get, :as => 'get_by_passcode'
    match '/update_device_token' => 'users#update_device_token', :via => :post, :as => 'update_device_token'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable,:token_authenticatable, :recoverable
           #:validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :authentication_token
  attr_accessible :name, :password, :username

  has_many :questions
  has_many :talks
  has_many :attendances
  has_many :attended_talks, :class_name => Talk, :through => :attendances, :source => :talk
  has_many :votes
  has_one :user_device_token

  validates_presence_of :username

  def joined?(talk)
    Attendance.where(:talk_id => talk.id, :user_id => self.id).count > 0
  end

  def owned?(talk)
    talk.user_id == self.id
  end

  def as_json(options={})
    super(:except =>[:password, :password_confirmation, :remember_me])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  before_filter :authenticate_user!
  before_filter :ensure_params_exist, :only => :update_device_token

  def ensure_params_exist
    return unless params[:device_token].blank?
    render :json=>{:success => FALSE_VALUE, :message=>"missing device token parameter"}, :status=>422
  end

  def update_device_token
    if current_user.nil?
      render :json => {:success => FALSE_VALUE, :message => "user not logged in"}, :status => 401
    else
      device_token = current_user.user_device_token || UserDeviceToken.new(:user_id => current_user.id)
      device_token.device_token = params[:device_token]
      if device_token.save
        render :json => {:success => TRUE_VALUE, :device_token => device_token}, :status => 200
      else
        render :json => {:success => FALSE_VALUE, :message => "Unable to update device token"}, :status => 422
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>